# Generated by Django 5.1.2 on 2024-10-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.URLField(blank=True, max_length=100, unique=True),
        ),
    ]
